### ISSUE TITLE
Cannot build KBAL on RHEL7

### ISSUE THREAD

**Issue by jhalverson** [chadhazlett/KBAL#15]
I am on RHEL 7.7 using GCC 8.3 and R 3.6.2. Below is the output when attempting to install KBAP:

> library(devtools)
Loading required package: usethis
> devtools::install_github("chadhazlett/KBAL")
Downloading GitHub repo chadhazlett/KBAL@master
✔  checking for file ‘/tmp/RtmpCyFK1a/remotes1993a14241de4/chadhazlett-KBAL-61af584/DESCRIPTION’ ...
─  preparing ‘kbal’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘kbal_0.1.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
Installing package into ‘/home/jdh4/R/x86_64-redhat-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘kbal’ ...
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/jdh4/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c Cpp_Kernelbuild.cpp -o Cpp_Kernelbuild.o
Cpp_Kernelbuild.cpp: In function ‘Rcpp::NumericMatrix new_gauss_kern(Rcpp::NumericMatrix, Rcpp::NumericMatrix, double)’:
Cpp_Kernelbuild.cpp:28:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < n1; ++i) {
                   ~~^~~~
Cpp_Kernelbuild.cpp:29:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int j = 0; j < n2; ++j) {
                     ~~^~~~
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/jdh4/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o kbal.so Cpp_Kernelbuild.o RcppExports.o -L/usr/lib64/R/lib -lR
installing to /home/jdh4/R/x86_64-redhat-linux-gnu-library/3.6/00LOCK-kbal/00new/kbal/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘kbal’
    finding HTML links ... done
    biasbound                               html  
    dimw                                    html  
    ebalance_custom                         html  
    getdist                                 html  
    getw                                    html  
    kbal                                    html  
    lalonde                                 html  
    makeK                                   html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘kbal’ in library.dynam(lib, package, package.lib):
 shared object ‘KBAL.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jdh4/R/x86_64-redhat-linux-gnu-library/3.6/kbal’
Error: Failed to install 'kbal' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpCyFK1a/file1993a7cf9afe9/kbal_0.1.tar.gz’ had non-zero exit status

Also, why are there object files and KBAL.so in /src on GitHub? Is KBAL intended for a specific architecture?

**Comment by chadhazlett** [comment]
Hello,
We will look into this! Also we are mid-update, so once we can push that
update we will let you know.
Best,
Chad

**Comment by jhalverson** [comment]
Haosen G. managed to complete the installation by experimenting with the dynamic 
path. It turns out that the problem is due to a mismatch in names: the actual .so file is 'kbal.so' while the command is looking for 'KBAL.so'. The problem then is solved after modifying the NAMESPACE in the git repo. And It seems that the name difference is a problem throughout the package.

**Comment by chadhazlett** [comment]
Thank you - this is my fault as I was just starting to change the name
over, but hadn't intended to commit yet. We will fix that up. Thanks!

**Comment by chadhazlett** [comment]
This should be addressed now, though we will continue to test.  Many
thanks.

**Comment by jhalverson** [comment]
Thank you. Everything is good now on our side.

Jon
